Add buzzer driver
abadr99/stm32f10xxx_cpp_interface pull request #29
Opened 2024-07-07 07:40 UTC by gehadHassanin

2024-07-15 06:24 UTC, noran97 reviewed
according to how you implement  enum BuzzerState you can use kOn directly instead of BuzzerState::kOn

2024-07-15 06:24 UTC, noran97 commented on dev/hal/inc/Buzzer.h
try to add A method to check the current state

2024-07-15 06:29 UTC, noran97 requested changes

2024-07-15 06:29 UTC, noran97 commented on dev/hal/src/Buzzer.cpp
according to your implementation of enum BuzzerState you can use kOn directly instead of BuzzerState::kOn

2024-08-04 19:56 UTC, abadr99 approved these changes

2024-08-04 19:56 UTC, merged